### ISSUE TITLE
Plugin not working for me on 1.13.2

### ISSUE THREAD

**Issue by mono323** [Pwn9/PwnBuckets#3]
Blocking is set to true water doesnt evaporate at all if placed water source blocks still possible World is enabled, also the discord link provided is not valid so cant contact im using PwnBuckets 1.4

**Comment by DreamPhreak** [comment]
This is the correct place to open the issue, but found a discord invite link that works: https://discordapp.com/invite/h9FfA7J
You're right, discord.pwn9.com link and the one on the main website both expired or something.

**Comment by msudol** [comment]
What is server version? Current release only supports Spigot version 1.13.x

**Comment by mono323** [comment]
server version 1.13.2

**Comment by mono323** [comment]
but PaperSpigot maybe thats the issue

**Comment by mono323** [comment]
self assigned? am i doing something wrong or just doesnt it work with paper?

**Comment by mono323** [comment]
should i send the log? even though i dont see anything PwnBucket related in there except the enabling message

**Comment by msudol** [comment]
how about a list of other plugins, and the config you are using.

**Comment by mono323** [comment]
AnimalApettite 1.2.1.jar  Cargo-1.3.0.jar   CustomCrafting-v1.3.3.0 (2).jar  Disease-3.1.1.jar  Languagy.jar  LuckPerms-Bukkit-4.4.1.jar  MCRealistic (5).jar  Multiverse-Core-3.0.0.jar  MythicMobs-4.5.9.jar  PlugMan.jar   PwnBuckets.jar  PwnPlantGrowth.jar   RealisticWorldGenerator-4.1.8.jar  Smeltery.jar  WolfyUtilities-v1.2.0.0 (1).jar   WorldBorder (1).jar  worldedit-bukkit-7.0.0.jar  worldedit-bukkit-7.0.0.jar

**Comment by mono323** [comment]
[config.zip](https://github.com/Pwn9/PwnBuckets/files/3366047/config.zip)

**Comment by mono323** [comment]
tested on 1.13.2 Craftbukkit not working either no error messages nothing... only this one plugin no other plugins its not working
[latest.log](https://github.com/Pwn9/PwnBuckets/files/3374380/latest.log)

**Comment by msudol** [comment]
> 
> 
> [config.zip](https://github.com/Pwn9/PwnBuckets/files/3366047/config.zip)

Looking at your config, you have everything set to false except ice_melt and dispenser, so none of that will work....  Your debug log is set to false so you won't get any debug info... 

```
# Which worlds should this plugin be enabled in? Worlds not in this list will not be affected
enabled_worlds:
  - Freebuild
  - New
  - Farmwelt

# Globally stop buckets from transporting water source blocks
block_water_bucket: false

# Biome bypass for water buckets, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
bucket_allowed_biomes: []

# Globally stop dispensers from transporting water source blocks
block_water_dispenser: true

# Biome bypass for dispensers, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
dispenser_allowed_biomes: []

# Globally stop ice melt from becoming source blocks
block_ice_melt: true

# Biome bypass for ice melt, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
ice_melt_allowed_biomes: []
   
# Globally stop buckets from transporting lava source blocks
block_lava_bucket: false   
   
# Biome bypass for lava buckets, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
lava_bucket_allowed_biomes: []
   
# Globally stop dispensers from transporting lava source blocks
block_lava_dispenser: false

# Biome bypass for lava dispensers, list type: [beach, ocean] (anything from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html)
lava_dispenser_allowed_biomes: []

# Optionally block creative users from placing source water/lava with buckets. Does not effect spawned in water/lava blocks.
block_creative_source: false

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false
```

**Comment by mono323** [comment]
also not working with block_water_bucket on true  i just realised its an old config

**Comment by msudol** [comment]
are you testing this as a user with no permissions, or as an OP?  because, OP has bypass and it won't work.

**Comment by mono323** [comment]
still doesnt work
i deop myself and wont work on 1.13.2

**Comment by mono323** [comment]
ok my bad im sorry i found my mistake
