### ISSUE TITLE
Water Bottles

### ISSUE THREAD

**Issue by kevATin** [Pwn9/PwnBuckets#5]
Sticking with the topic of keeping water finite, I think (water) bottles could use a makeover.

How about a feature that allows admins to set a chance that filling a glass bottle with water causes the source to vanish/ become empty.
Ideally each bottle should slowly degrade the total water amount of a source block, but in reality that would require keeping track of every water block's volume and figuring out a way to visualize less than full water sources. So simply using chances seems like a good compromise.

Ideas for Settings:
bottleSourceVanishChance = 0,1 (10%)
Means that each time a glass bottle is used on any source block it has a 10% chance to replace it with an air block.
0 is off, 1 is 100%

bottleCauldronEmptyChance = 0,25 (25%)
Means that each time a glass bottle is used on a cauldron that contains water it has a 25% chance to remove 1 of the 3 water fill levels from it.
0 is off, 1 is 100%

With default values like this players would have a small incentive, if my math hasn't failed me, to put their water into buckets and then into cauldrons, and from there into bottles. That way cauldrons retain their use, while the water "economy" isn't completely broken and imbalanced.
I was considering whether it would make sense to let bottles reduce a cauldron's water level by 2 or 3, but given that water bottles can be used to fill cauldrons, this would have quite a high potential to mess up the balance; so probably better not.

**Comment by msudol** [comment]
Out of scope for this plugin, maybe as an idea for a standalone.
